### ISSUE TITLE
'mongodb' is not the name of a known user

### ISSUE THREAD

**Issue by L-YW** [L-YW/Coral_simple#10]
도커 컴포즈를 통해 도커 컨테이너를 생성 후
- ```docker-compose.yml```
```
version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=keti1234
      - MONGO_INITDB_DATABASE=project
    volumes:
      - ~/mongo_db:/data/db
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "27017:27107"
```

- 다음과 같은 문제 발생
```
Error response from daemon: Container c966e54bcd87507ac2704d98e3f5c3828684e980d3607fa1213a00cf758ebec4 is restarting, wait until the container is running
```

#### - 컨테이너의 상태가 계속 'Restarting'에서 멈춰있음. 발생 원인을 파악하기 위해 로그를 찍어봄
```
$ docker logs --tail 50 --follow --timestamps keti_mongo_1
```

- 문제의 원인 로그
```
2021-11-01T06:10:26.745273939Z find: 'mongodb' is not the name of a known user
```

### - 해결 방법 : ```volume```이 문제였을지도..(지우니까 해결됨)
